FROM python:3.11-slim

WORKDIR /app

ENV API_BASE_URL=http://api:8000

COPY ui/requirements_ui.txt ./requirements_ui.txt
RUN pip install --no-cache-dir -r requirements_ui.txt

COPY ui ./ui

EXPOSE 8501

CMD ["streamlit", "run", "ui/app.py", "--server.address=0.0.0.0", "--server.port=8501"]
